### ISSUE TITLE
addition does not work

### ISSUE THREAD

**Issue by MarkSwanson** [bgkillas/kalc#7] opened 2023-08-06 01:14 UTC
I'm getting some weird results when adding 2 numbers together.
> 47 + 42 
1.974e3

> 47 + 42 + 5.51
543837/50
1.087674e4

$ cat -p ~/.config/kalc.config 
sci=true
deg or grad or rad
base=10
tau=false
polar=false
frac=true
rt=false
deci=12
color=true
prompt=true
comma=false
prec=512
frac_iter=50
xr=-10,10
yr=-10,10
zr=-10,10
2d=20000
3d=400
point=.
line=false
multi=false
tabbed=false
vars=true
debug=false
small_e=true

**Comment by bgkillas** [comment] 2023-08-06 01:45
i sure did an oopsie, i really should test with spaces more, should be fixed now in master, probably alot of other space related bugs, however i removed '5 2' being assumed to be 5*2(now 52) other assumed multiplications still apply just not one caused by spaces. hopefully i find a way to fix nicely

**Closed as completed by bgkillas** 2023-08-06 01:45 UTC

**Comment by bgkillas** [comment] 2023-08-06 01:51
fixed multiplication issue
